class Path:
    INPUT_CNPJ = '//*[@id="CNPJ"]'
    BOX_NFe = '//*[@id="ModeloNFE"]'
    BOX_NFCe = '//*[@id="ModeloNFCE"]'
    BOX_TOTALIZADO = '//*[@id="PorCFOP"]'
    INPUT_DATA_INI = '//*[@id="DtPeriodoInicio"]'
    INPUT_DATA_FIM = '//*[@id="DtPeriodoFim"]'
    BOX_NF_SAIDAS = '//*[@id="SaidaEmitente"]'
    BOX_NF_COMPRAS = '//*[@id="SaidaDestinatario"]'
    BOX_NF_PROPRIAS = '//*[@id="EntradaEmitente"]'
    BOX_SIT_NORMAL = '//*[@id="NFeNormal"]'
    BOX_SIT_CANCEL = '//*[@id="NFeCancelada"]'
    BOTAO_CONSULTAR = '//*[@id="NFe"]/fieldset/fieldset[1]/div[2]/table/tbody/tr/td/input'
    BOTAO_IMPRIMIR = '//*[@id="imprimir"]/a'
    BOX_NF_TERCEIROS = '//*[@id="EntradaRemetente"]'
